apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: champi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/noiseoverip/ai-apps
    targetRevision: HEAD
    path: manifests/champi
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
